### ISSUE TITLE
Warning in linter

### ISSUE THREAD

**Issue by Jcornmanhomonoff** [ga-wdi-boston/project-issue-tracker-guide#6]
My linter is giving me a warning asking me to move my code around and merge 'a' and 'a:hover' with '.navigation'. However, it is working as I like it to right now and when I adjust accordingly, it stops working.
<img width="665" alt="screen shot 2016-04-05 at 2 21 41 pm" src="https://cloud.githubusercontent.com/assets/17557070/14293247/c2d1e7bc-fb39-11e5-8e8e-e20ee6c413e9.png">

**Comment by Jcornmanhomonoff** [comment]
.navigation {
  background: $deepskyblue;
  display: -webkit-box;
  display: -moz-box;
  display: -ms-flexbox;
  // display: -webkit-flex;
  display: flex;
  justify-content: flex-end;
  list-style: none;
  margin: 0;
  // -webkit-flex-flow: row wrap;
}

.navigation a {
  color: $white;
  display: block;
  padding: 1em;
  text-decoration: none;
  }

.navigation a:hover {
  background: darken($deepskyblue, 2%);
}

**Comment by Jcornmanhomonoff** [comment]
``` css
.navigation {
  background: $deepskyblue;
  display: -webkit-box;
  display: -moz-box;
  display: -ms-flexbox;
  // display: -webkit-flex;
  display: flex;
  justify-content: flex-end;
  list-style: none;
  margin: 0;
  // -webkit-flex-flow: row wrap;
}

.navigation a {
  color: $white;
  display: block;
  padding: 1em;
  text-decoration: none;
  }

.navigation a:hover {
  background: darken($deepskyblue, 2%);
}
```
